### ISSUE TITLE
JSON-LD deserializer fails to parse ids:byteSize value

### ISSUE THREAD

**Issue by newinnovations** [eclipse-edc/Connector#1870]
# Bug Report

## Describe the Bug
I am testing interworking between the EDC and the TSG (TNO Security Gateway). The TSG is a pure IDS connector.

In one use case the EDC sends an `ids:DescriptionRequestMessage` to the TSG and receives an `ids:DescriptionResponseMessage` back with the following payload:

```
  1: {
  2:   "@context" : {
  3:     "ids" : "https://w3id.org/idsa/core/",
  4:     "idsc" : "https://w3id.org/idsa/code/"
  5:   },
  6:   "@type" : "ids:BaseConnector",
  7:   "@id" : "urn:connector:tno:playground:tsg:company2",
  8:   "ids:publicKey" : {
  9:     "@type" : "ids:PublicKey",
 10:     "@id" : "https://w3id.org/idsa/autogen/publicKey/6184bfe3-c4b9-404c-aab5-e16b3c05bed1",
 11:     "ids:keyValue" : "TUlJR...dMZzli",
 12:     "ids:keyType" : {
 13:       "@id" : "https://w3id.org/idsa/code/RSA"
 14:     }
 15:   },
 16:   "ids:description" : [ {
 17:     "@value" : "TNO EDC Playground - TSG Company 2",
 18:     "@type" : "http://www.w3.org/2001/XMLSchema#string"
 19:   } ],
 20:   "ids:title" : [ {
 21:     "@value" : "TNO EDC Playground - TSG Company 2",
 22:     "@type" : "http://www.w3.org/2001/XMLSchema#string"
 23:   } ],
 24:   "ids:securityProfile" : {
 25:     "@id" : "https://w3id.org/idsa/code/BASE_SECURITY_PROFILE"
 26:   },
 27:   "ids:resourceCatalog" : [ {
 28:     "@type" : "ids:ResourceCatalog",
 29:     "@id" : "urn:connector:tno:playground:tsg:company2:resources",
 30:     "ids:offeredResource" : [ {
 31:       "@type" : "ids:DataResource",
 32:       "@id" : "urn:playground:artificats:company2:demo-artifact",
 33:       "ids:language" : [ {
 34:         "@id" : "https://w3id.org/idsa/code/EN"
 35:       } ],
 36:       "ids:version" : "1",
 37:       "ids:keyword" : [ {
 38:         "@value" : "for",
 39:         "@language" : "en"
 40:       }, {
 41:         "@value" : "an",
 42:         "@language" : "en"
 43:       }, {
 44:         "@value" : "this",
 45:         "@language" : "en"
 46:       }, {
 47:         "@value" : "testing",
 48:         "@language" : "en"
 49:       }, {
 50:         "@value" : "artifact",
 51:         "@language" : "en"
 52:       }, {
 53:         "@value" : "used",
 54:         "@language" : "en"
 55:       }, {
 56:         "@value" : "is",
 57:         "@language" : "en"
 58:       } ],
 59:       "ids:description" : [ {
 60:         "@value" : "This is an artifact used for testing",
 61:         "@language" : "en"
 62:       } ],
 63:       "ids:contractOffer" : [ {
 64:         "@type" : "ids:ContractOffer",
 65:         "@id" : "https://w3id.org/idsa/autogen/contractOffer/b6138098-df92-40ae-b5ff-6492c28410fc",
 66:         "ids:permission" : [ {
 67:           "@type" : "ids:Permission",
 68:           "@id" : "https://w3id.org/idsa/autogen/permission/319b0b0f-591f-40b3-a080-9abf295f8674",
 69:           "ids:target" : {
 70:             "@id" : "urn:connector:tno:playground:tsg:company2:artifacts:c2752e20-2ab4-47c5-9563-9963bde4185b"
 71:           },
 72:           "ids:action" : [ {
 73:             "@id" : "https://w3id.org/idsa/code/READ"
 74:           }, {
 75:             "@id" : "https://w3id.org/idsa/code/USE"
 76:           } ]
 77:         } ],
 78:         "ids:contractStart" : {
 79:           "@value" : "2022-01-01T00:00:00.000Z",
 80:           "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
 81:         },
 82:         "ids:contractEnd" : {
 83:           "@value" : "2022-12-31T00:00:00.000Z",
 84:           "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
 85:         }
 86:       } ],
 87:       "ids:title" : [ {
 88:         "@value" : "Demo artifact",
 89:         "@language" : "en"
 90:       } ],
 91:       "ids:representation" : [ {
 92:         "@type" : "ids:Representation",
 93:         "@id" : "https://w3id.org/idsa/autogen/representation/c88cf494-cf7f-4568-b522-d48c9fdbe51e",
 94:         "ids:instance" : [ {
 95:           "@type" : "ids:Artifact",
 96:           "@id" : "urn:connector:tno:playground:tsg:company2:artifacts:c2752e20-2ab4-47c5-9563-9963bde4185b",
 97:           "ids:fileName" : "demo-artifact.txt",
 98:           "ids:byteSize" : 74
 99:         } ],
100:         "ids:mediaType" : {
101:           "@type" : "ids:IANAMediaType",
102:           "@id" : "https://w3id.org/idsa/autogen/iANAMediaType/02e1fdab-eb6b-4ae9-abc0-9cb90a871ff8",
103:           "ids:filenameExtension" : "txt"
104:         }
105:       } ],
106:       "ids:resourceEndpoint" : [ {
107:         "@type" : "ids:ConnectorEndpoint",
108:         "@id" : "https://w3id.org/idsa/autogen/connectorEndpoint/6b7eaa94-9356-4a6c-a815-359971878f61",
109:         "ids:path" : "/artifacts/urn%3Aplayground%3Aartificats%3Acompany2%3Ademo-artifact",
110:         "ids:accessURL" : {
111:           "@id" : "https://company2.ids.eclipsedataspace.com/router"
112:         }
113:       } ],
114:       "ids:created" : {
115:         "@value" : "2022-08-23T14:04:11.896Z",
116:         "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
117:       },
118:       "ids:publisher" : {
119:         "@id" : "urn:tno:playground:company2"
120:       },
121:       "ids:sovereign" : {
122:         "@id" : "urn:tno:playground:company2"
123:       },
124:       "ids:standardLicense" : {
125:         "@id" : "http://www.apache.org/licenses/LICENSE-2.0"
126:       }
127:     } ]
128:   } ],
129:   "ids:inboundModelVersion" : [ "4.2.6", "4.2.7", "4.2.0", "4.2.1", "4.1.2", "4.0.0", "4.1.0", "4.2.4", "4.2.5", "4.2.2", "4.2.3" ],
130:   "ids:outboundModelVersion" : "4.2.7",
131:   "ids:hasDefaultEndpoint" : {
132:     "@type" : "ids:ConnectorEndpoint",
133:     "@id" : "https://w3id.org/idsa/autogen/connectorEndpoint/ab4c0197-6c85-4a9a-a656-f7fb8f709cea",
134:     "ids:accessURL" : {
135:       "@id" : "https://company2.ids.eclipsedataspace.com/router"
136:     }
137:   },
138:   "ids:hasEndpoint" : [ {
139:     "@type" : "ids:ConnectorEndpoint",
140:     "@id" : "https://w3id.org/idsa/autogen/connectorEndpoint/ab4c0197-6c85-4a9a-a656-f7fb8f709cea",
141:     "ids:accessURL" : {
142:       "@id" : "https://company2.ids.eclipsedataspace.com/router"
143:     }
144:   } ],
145:   "ids:maintainer" : {
146:     "@id" : "urn:tno:playground:company2"
147:   },
148:   "ids:curator" : {
149:     "@id" : "urn:tno:playground:company2"
150:   }
151: }
```

Parsing fails on the `ids:byteSize` with `Could not read BigInteger` at line: 98, column: 30 of the payload (through reference chain: ... `de.fraunhofer.iais.eis.ArtifactImpl["ids:byteSize"]`). Full error below:

```
S 2022-08-23 17:20:48 | JerseyExtension: Unexpected exception caught
org.eclipse.dataspaceconnector.spi.EdcException: Could not deserialize connector self-description: Could not read BigInteger
 at [Source: (byte[])"{
  "@context" : {
    "ids" : "https://w3id.org/idsa/core/",
    "idsc" : "https://w3id.org/idsa/code/"
  },
  "@type" : "ids:BaseConnector",
  "@id" : "urn:connector:tno:playground:tsg:company2",
  "ids:publicKey" : {
    "@type" : "ids:PublicKey",
    "@id" : "https://w3id.org/idsa/autogen/publicKey/6184bfe3-c4b9-404c-aab5-e16b3c05bed1",
    "ids:keyValue" : "TUlJRVdEQ0NBMENnQXdJQkFnSUJBREFOQmdrcWhraUc5dzBCQVFzRkFEQ0JpREVMTUFrR0ExVUVCaE1DVGt3eEVqQVFCZ05WQkFnVENVZHliMjVwYm1kbGJqRVNNQkFHQTFVRUJ"[truncated 6731 bytes]; line: 98, column: 30] (through reference chain: de.fraunhofer.iais.eis.BaseConnectorImpl["ids:resourceCatalog"]->java.util.ArrayList[0]->de.fraunhofer.iais.eis.ResourceCatalogImpl["ids:offeredResource"]->java.util.ArrayList[0]->de.fraunhofer.iais.eis.DataResourceImpl["ids:representation"]->java.util.ArrayList[0]->de.fraunhofer.iais.eis.RepresentationImpl["ids:instance"]->java.util.ArrayList[0]->de.fraunhofer.iais.eis.ArtifactImpl["ids:byteSize"])
	at org.eclipse.dataspaceconnector.ids.api.multipart.dispatcher.sender.MultipartCatalogDescriptionRequestSender.getBaseConnector(MultipartCatalogDescriptionRequestSender.java:153)
	at org.eclipse.dataspaceconnector.ids.api.multipart.dispatcher.sender.MultipartCatalogDescriptionRequestSender.getResponseContent(MultipartCatalogDescriptionRequestSender.java:114)
	at org.eclipse.dataspaceconnector.ids.api.multipart.dispatcher.sender.IdsMultipartSender.lambda$send$0(IdsMultipartSender.java:211)
	at org.eclipse.dataspaceconnector.ids.core.message.FutureCallback.onResponse(FutureCallback.java:45)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
I 2022-08-23 17:20:48 | HTTP | GET  | /api/v1/data/catalog | 10.244.2.8 | PostmanRuntime/7.29.2
```

I have not seen this error with EDC-EDC exchanges, but in those cases the byteSize was not provided as the assets were located in the 'cloud' and not known to the EDC.

### Expected Behavior
That the JSON-LD deserializer would be able to parse the `ids:byteSize` value.

**Comment by juliapampus** [comment]
As I see, the TSG provides the byteSize as `"ids:byteSize" : 74`. The EDC expects it to be 
```
"ids:byteSize" : { 
   "@id": "74",
   "@value": "http://www.w3.org/2001/XMLSchema#integer"
}
```

We would need to modify the serializer in a way that it would allow missing type information.

**Comment by newinnovations** [comment]
From discussions with Markus Spiekermann we know that backward compatibility with IDS is not a priority for the project. But others may want to build extensions to support "legacy" IDS connectors. It would help if the JSON-LD implementation of the EDC would be compatible with the Fraunhofer infomodel-serializer which I think the TSG uses. And `"ids:byteSize" : 74` is valid JSON-LD isn't it?

**Comment by jimmarino** [comment]
There will still be the issue that the wire protocols are incompatible, so I'm not sure supporting alternative serialization forms is going to help. 

Regarding the info-model serializer, we discovered serious concurrency issues with the latter that cannot easily be fixed. Our goal is to replace the existing info model library with a new one. This should track with evolving the IDS standards to support async message patterns.
