### ISSUE TITLE
Error when file transfer or contract negotiation is rejected

### ISSUE THREAD

**Issue by siskavera** [eclipse-edc/Connector#2447]
# Bug Report

## Describe the Bug
The connector throws an error when a contract negotiation or file transfer is rejected, instead of a clean rejection message. I am unsure if this is intended, but it makes it difficult to debug why the request was rejected.

### Expected Behavior
Rejection message with the reason for rejection.

### Observed Behavior
When file transfer or contract negotiation is rejected for any reason (e.g. wrongly configured request), an error is thrown, complaining about the message type. Only `RejectionMessageImpl` is accepted, `RequestInProcessMessageImpl` is not.

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: org.eclipse.edc.spi.EdcException: Received class de.fraunhofer.iais.eis.RejectionMessageImpl but expected [class de.fraunhofer.iais.eis.RequestInProcessMessageImpl].
2023-01-31T14:11:26.080643119Z 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
2023-01-31T14:11:26.080652901Z 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
2023-01-31T14:11:26.080661502Z 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
2023-01-31T14:11:26.080669655Z 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
2023-01-31T14:11:26.080678536Z 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
2023-01-31T14:11:26.080686301Z 	at dev.failsafe.spi.FailsafeFuture.completeResult(FailsafeFuture.java:97)
2023-01-31T14:11:26.080694629Z 	at dev.failsafe.AsyncExecutionImpl.complete(AsyncExecutionImpl.java:159)
2023-01-31T14:11:26.080699509Z 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
2023-01-31T14:11:26.080704831Z 	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
2023-01-31T14:11:26.080720855Z 	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
2023-01-31T14:11:26.080729082Z 	at dev.failsafe.AsyncExecutionImpl.executeAsync(AsyncExecutionImpl.java:149)
2023-01-31T14:11:26.080736087Z 	at dev.failsafe.AsyncExecutionImpl.record(AsyncExecutionImpl.java:100)
2023-01-31T14:11:26.080743779Z 	at dev.failsafe.AsyncExecutionImpl.recordResult(AsyncExecutionImpl.java:106)
2023-01-31T14:11:26.080752218Z 	at dev.failsafe.okhttp.FailsafeCall$1.onResponse(FailsafeCall.java:145)
2023-01-31T14:11:26.080780646Z 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
2023-01-31T14:11:26.080789517Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-01-31T14:11:26.080796934Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-01-31T14:11:26.080801913Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-01-31T14:11:26.080808396Z Caused by: java.lang.RuntimeException: org.eclipse.edc.spi.EdcException: Received class de.fraunhofer.iais.eis.RejectionMessageImpl but expected [class de.fraunhofer.iais.eis.RequestInProcessMessageImpl].
2023-01-31T14:11:26.080815183Z 	at org.eclipse.edc.protocol.ids.api.multipart.dispatcher.sender.IdsMultipartSender.lambda$send$0(IdsMultipartSender.java:171)
2023-01-31T14:11:26.080822373Z 	at org.eclipse.edc.connector.core.base.EdcHttpClientImpl.lambda$executeAsync$1(EdcHttpClientImpl.java:81)
2023-01-31T14:11:26.080829795Z 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
2023-01-31T14:11:26.080837626Z 	... 15 more
2023-01-31T14:11:26.080864802Z Caused by: org.eclipse.edc.spi.EdcException: Received class de.fraunhofer.iais.eis.RejectionMessageImpl but expected [class de.fraunhofer.iais.eis.RequestInProcessMessageImpl].
2023-01-31T14:11:26.080875700Z 	at org.eclipse.edc.protocol.ids.api.multipart.dispatcher.sender.IdsMultipartSender.checkResponseType(IdsMultipartSender.java:223)
2023-01-31T14:11:26.080884513Z 	at org.eclipse.edc.protocol.ids.api.multipart.dispatcher.sender.IdsMultipartSender.lambda$send$0(IdsMultipartSender.java:166)
2023-01-31T14:11:26.080893976Z 	... 17 more
```

## Steps to Reproduce
1. Set up a policy and an asset for a producer.
2. Initiate a transfer process or a contract negotiation with parameters not accepted by the producer.

## Context Information
- Used version: snapshot (0.0.1-SNAPSHOT)
- OS: Ubuntu, with each connector run as a docker docker container in a single docker-compose application
- HTTP file transfer

## Possible Implementation
I am new to EDC, but maybe the function `getAllowedResponseTypes` in the classes `MultipartContractOfferSender` and `MultipartArtifactRequestSender` should allow also `RejectionMessageImpl`?

**Comment by jimmarino** [comment]
This is either due to the bug you outlined (the EDC doesn't allow for the rejection message type) or an invalid message sent by the other end. Since the code in question will be replaced by code supporting the new IDS protocol (where this type of thing can't happen), it's likely this won't be fixed.

**Comment by ndr-brt** [comment]
Closing as it's referring to the old protocol
