### ISSUE TITLE
The column name agr_id was not found in this ResultSet

### ISSUE THREAD

**Issue by dilipdhankecha2530** [eclipse-edc/Connector#2692]
# Bug Report

## Describe the Bug
Done the migration from the schema.sql file to my database.

### Expected Behavior
An error must not be there.

### Observed Behavior
`[2023-04-07 11:33:53] [SEVERE ] StateMachineManager [consumer-contract-negotiation] error caught
org.eclipse.edc.spi.persistence.EdcPersistenceException: org.postgresql.util.PSQLException: The column name agr_id was not found in this ResultSet.
	at org.eclipse.edc.sql.SqlQueryExecutor$1.tryAdvance(SqlQueryExecutor.java:123)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.eclipse.edc.connector.store.sql.contractnegotiation.store.SqlContractNegotiationStore.lambda$nextForState$8(SqlContractNegotiationStore.java:178)
	at org.eclipse.edc.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:74)
	at org.eclipse.edc.connector.store.sql.contractnegotiation.store.SqlContractNegotiationStore.nextForState(SqlContractNegotiationStore.java:172)
	at org.eclipse.edc.connector.contract.negotiation.ConsumerContractNegotiationManagerImpl.lambda$processNegotiationsInState$16(ConsumerContractNegotiationManagerImpl.java:359)
	at org.eclipse.edc.statemachine.StateProcessorImpl.process(StateProcessorImpl.java:46)
	at java.base/java.util.stream.ReferencePipeline$5$1.accept(ReferencePipeline.java:231)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.LongPipeline.reduce(LongPipeline.java:498)
	at java.base/java.util.stream.LongPipeline.sum(LongPipeline.java:456)
	at org.eclipse.edc.statemachine.StateMachineManager.performLogic(StateMachineManager.java:118)
	at org.eclipse.edc.statemachine.StateMachineManager.lambda$loop$2(StateMachineManager.java:106)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.postgresql.util.PSQLException: The column name agr_id was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:3033)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2888)
	at org.eclipse.edc.connector.store.sql.contractnegotiation.store.SqlContractNegotiationStore.mapContractAgreement(SqlContractNegotiationStore.java:290)
	at org.eclipse.edc.connector.store.sql.contractnegotiation.store.SqlContractNegotiationStore.extractContractAgreement(SqlContractNegotiationStore.java:333)
	at org.eclipse.edc.connector.store.sql.contractnegotiation.store.SqlContractNegotiationStore.mapContractNegotiation(SqlContractNegotiationStore.java:314)
	at org.eclipse.edc.sql.SqlQueryExecutor$1.tryAdvance(SqlQueryExecutor.java:120)
	... 29 more
`
## Steps to Reproduce
1. Add all tables from sql file to database
2. Execute the steps till contract negotiation
3. Now the error is there in logs.

**Comment by wolf4ood** [comment]
Hi @dilipdhankecha2530 

thanks for raising this issue. Which version are you using of EDC?

Thanks

**Comment by dilipdhankecha2530** [comment]
@wolf4ood 
Latest code of the repo.

**Comment by wolf4ood** [comment]
@dilipdhankecha2530 

i was able to reproduce it. I'm working on a fix in PR #2694

**Comment by dilipdhankecha2530** [comment]
@wolf4ood 
Thanks for quick support.
