### ISSUE TITLE
File name changes to the target bucket name while transferring it from one AWS S3 bucket to another AWS S3 bucket  using Connector

### ISSUE THREAD

**Issue by MUsman1992** [eclipse-edc/Connector#2997]
I am transferring file from one AWS S3 bucket to another AWS S3 bucket using the Connector. I am using the latest tag `v0.0.1-milestone-8`. I am facing a small issue. Actually, when files ae copied from one bucket to another bucket, files are not copied with their actual names and file extension. Instead the name of the file changes to the target bucket name created on the consumer side during the execution of S3ProvisionPipeline. 

<img width="1000" alt="S3_bucket_details" src="https://github.com/eclipse-edc/Connector/assets/62036653/6d22fced-4a35-4ace-ad0c-9e33d4d59297">

The body of my request `http://localhost:9192/api/v1/management/transferprocess` is given below:

```
{
  "connectorAddress": "http://localhost:8282/api/v1/ids/data",
  "protocol": "ids-multipart",
  "connectorId": "consumer",
  "assetId": "1",
  "contractId": "1:956a102a-f790-485a-bd03-88f35714aba6",
  "dataDestination": {
    "properties": {
      "type": "AmazonS3",
      "region": "eu-central-1",
      "bucketName": "eclipse-dataspace-connector-bucket-13",
      "keyName": "application_configurations.txt"


    },
    "type": "AmazonS3"
  },
  "managedResources": true,
  "transferType": {
    "contentType": "text/plain",
    "isFinite": true
  }
}

```

During debugging, I have found out that on the consumer side, when AWS resources are created the DataAddress object is updated due to which i think we are facing this issue. https://github.com/eclipse-edc/Connector/blob/v0.0.1-milestone-8/core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java#L494 Can anyone guide me how I can fix this or is this a bug?

**Comment by ndr-brt** [comment]
Hey, taking a quick look I'd say that the problem is that the `keyName` is not passed to the `S3BucketResourceDefinition` in the [`S3ConsumerResourceDefinitionGenerator`](https://github.com/eclipse-edc/Connector/blob/0a8bf896b91fe9307d7c4e1e35a7de73c59318e5/extensions/control-plane/provision/provision-aws-s3/src/main/java/org/eclipse/edc/connector/provision/aws/s3/S3ConsumerResourceDefinitionGenerator.java#L31) and the `ProvisionedResource` `resourceName` is set with the `bucketName` instead of the `keyName` in the [`S3BucketProvisioner`](https://github.com/eclipse-edc/Connector/blob/0a8bf896b91fe9307d7c4e1e35a7de73c59318e5/extensions/control-plane/provision/provision-aws-s3/src/main/java/org/eclipse/edc/connector/provision/aws/s3/S3BucketProvisioner.java#L94)

I'd say that this could be considered a bug. It would be great if you'd provide a PR to fix it

**Comment by MUsman1992** [comment]
Hey, thanks for the reply. Ok, I shall create a PR and add changes to fix this issue.

**Comment by MUsman1992** [comment]
I have solved this issue by making some changes in the code of AWS extensions. Now the `keyName` in the dataDestination represents the name of the file that will be transferred to the destination S3 bucket but now I am facing another issue. I am getting this exception:

```
DEBUG 2023-05-20T01:29:08.5410094 Transferring from AmazonS3 to AmazonS3.
SEVERE 2023-05-20T01:29:08.8422872 Error writing the data.txt object on the eclipse-dataspace-connector-bucket-50 bucket: The AWS Access Key Id you provided does not exist in our records. (Service: S3, Status Code: 403, Request ID: CT595RPWNJQ8GSV0, Extended Request ID: vyfMkhGyUS+I4CJ880z9VC7kYhpYNrAF/R4SzGG+Flc3B11tYUMwxqp+ya7JaWAGmLIJ+Gyk/s0=)
software.amazon.awssdk.services.s3.model.S3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: S3, Status Code: 403, Request ID: CT595RPWNJQ8GSV0, Extended Request ID: vyfMkhGyUS+I4CJ880z9VC7kYhpYNrAF/R4SzGG+Flc3B11tYUMwxqp+ya7JaWAGmLIJ+Gyk/s0=)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$0(BaseSyncClientHandler.java:68)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:62)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:52)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:63)
	at software.amazon.awssdk.services.s3.DefaultS3Client.getObject(DefaultS3Client.java:4580)
	at software.amazon.awssdk.services.s3.S3Client.getObject(S3Client.java:8077)
	at org.eclipse.edc.connector.dataplane.aws.s3.S3DataSource$S3Part.openStream(S3DataSource.java:66)
	at org.eclipse.edc.connector.dataplane.aws.s3.S3DataSink.transferParts(S3DataSink.java:48)
	at org.eclipse.edc.connector.dataplane.util.sink.ParallelSink.lambda$processPartsAsync$4(ParallelSink.java:83)
	at org.eclipse.edc.spi.telemetry.Telemetry.lambda$contextPropagationMiddleware$2(Telemetry.java:102)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I am using `vault-filesystem` extension to store the secrets. When I tried to debug that issue, I found out that when the request of data transfer is received by the provider connector, the secrets such as the consumer S3 bucket credentials are stored on the producer side in the vault https://github.com/eclipse-edc/Connector/blob/main/data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/handler/ArtifactRequestHandler.java#L162 Now as keyName represents the filename instead of the bucket name, when provider tries to transfer the data from the source https://github.com/eclipse-edc/Connector/blob/main/extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java#L81 , it uses consumer S3 bucket credentials because secret is accessed by the keyName, now keyName reprsents the filename that is same for both sourceDataAddress and destinationDataAddress due to which provider uses wrong credentials to access the source S3 bucket and as a result I am getting this error. I was wondering how we should solve the issue. Also I think, secrets should be identified by the bucket name because bucket names are unique but filenames  can be same for different scenarios. Also it's not easy to make changes in the code in this file https://github.com/eclipse-edc/Connector/blob/main/data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/handler/ArtifactRequestHandler.java#L162 because this code is used almost in all scenarios.

**Comment by ndr-brt** [comment]
@MUsman1992 yes, we discovered this issue in the #3042 so if you pull the latest nightly artifact the bug will be already solved, will be part of the next release

**Comment by MUsman1992** [comment]
@ndr-brt thanks for the reply. Yes, I have noticed that in main branch, ids modules have been removed which means that now only dsp protocol can be used for communication between 2 connectors. I have faced some new issues when I switched to the dsp protocol and tried to transfer data from one S3 bucket to another S3 bucket:

1. My `http://localhost:9192/api/v1/management/catalog/request` call was not successfully working. As a result, I had to replace this line in the code https://github.com/eclipse-edc/Connector/blob/main/extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/CatalogApiController.java#L88 with this `service.request(providerUrl, "dataspace-protocol-http", spec)` then it started working successfully. 
2. In the `S3BucketProvisionedResource `class https://github.com/eclipse-edc/Connector/blob/main/extensions/control-plane/provision/provision-aws-s3/src/main/java/org/eclipse/edc/connector/provision/aws/s3/S3BucketProvisionedResource.java, I had to replace these properties names `bucketName` and `region` with `https://w3id.org/edc/v0.0.1/ns/bucketName` and  `https://w3id.org/edc/v0.0.1/ns/region` otherwise during serialization when the JSON-LD structure is compacted it removes the  `bucketName` and `region` https://github.com/eclipse-edc/Connector/blob/main/data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/serialization/JsonLdRemoteMessageSerializerImpl.java#L58 due to which I get errors on the producer side when validations are performed on the DataAddress Object https://github.com/eclipse-edc/Connector/blob/main/extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactory.java#L82.

**Comment by ndr-brt** [comment]
@MUsman1992 the old management API has been deprecated as well, please use the `v2` with json-ld semantics

**Comment by MUsman1992** [comment]
@ndr-brt thanks for the reply. Yes, its working with the latest API, I have checked it now.
