### ISSUE TITLE
Getting Exception while runnning main branch code when data-plane-aws-s3 extension tries to transfer data from one S3 bucket to another S3 bucket 

### ISSUE THREAD

**Issue by MUsman1992** [eclipse-edc/Connector#3045]
I am facing an issue while transferring data from one S3 bucket to another S3 bucket using Connector. For storing secrets, I am using the vault-filesystem extension https://github.com/eclipse-edc/Connector/tree/main/extensions/common/vault/vault-filesystem For transferring data from one S3 bucket to another S3 bucket, I am using this extension data-plane-aws-s3 https://github.com/eclipse-edc/Connector/tree/main/extensions/data-plane/data-plane-aws-s3 When the data-plane-aws-s3 tries to perform data transfer, i am getting this exception

```
SEVERE 2023-05-19T16:04:16.0392186 Error writing the data.txt object on the eclipse-dataspace-connector-bucket-42 bucket: The AWS Access Key Id you provided does not exist in our records. (Service: S3, Status Code: 403, Request ID: MHPFZ7ME6VR6CSBD, Extended Request ID: 8ZBBrEeXec665jDZOFluVL304fOZ1e2wiD4UmWkGO3A4LDIykQkPNaROyI544ajcTHrGMZjhUWw=)
software.amazon.awssdk.services.s3.model.S3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: S3, Status Code: 403, Request ID: MHPFZ7ME6VR6CSBD, Extended Request ID: 8ZBBrEeXec665jDZOFluVL304fOZ1e2wiD4UmWkGO3A4LDIykQkPNaROyI544ajcTHrGMZjhUWw=)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$0(BaseSyncClientHandler.java:68)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:62)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:52)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:63)
	at software.amazon.awssdk.services.s3.DefaultS3Client.getObject(DefaultS3Client.java:4580)
	at software.amazon.awssdk.services.s3.S3Client.getObject(S3Client.java:8077)
	at org.eclipse.edc.connector.dataplane.aws.s3.S3DataSource$S3Part.openStream(S3DataSource.java:66)
	at org.eclipse.edc.connector.dataplane.aws.s3.S3DataSink.transferParts(S3DataSink.java:48)
	at org.eclipse.edc.connector.dataplane.util.sink.ParallelSink.lambda$processPartsAsync$4(ParallelSink.java:83)
	at org.eclipse.edc.spi.telemetry.Telemetry.lambda$contextPropagationMiddleware$2(Telemetry.java:102)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)


```

Another thing that I have noticed is that previouly I was using `v0.0.1-milestone-8` release and I did not face such issue but when I used `main `branch code, I am now getting this error. Also in data-plane-aws-s3 extension, inside the S3DataSourceFactory.java class, I have seen some differences between the main branch code https://github.com/eclipse-edc/Connector/blob/main/extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java#L81 and the  v0.0.1-milestone-8 release code https://github.com/eclipse-edc/Connector/blob/v0.0.1-milestone-8/extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java#L67 I have also noticed one thing while debugging on this line https://github.com/eclipse-edc/Connector/blob/main/extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java#L81 if I set `secret` to null or if I set correct values inside the `accessKeyId` and `secretAccessKey` present inside the secret, the code successfully works. I am not sure but maybe the application is not setting the correct values of the  `accessKeyId` and `secretAccessKey` in the `secret` object. Below it can also be seen in the image that represents the secrets stored in the vault-filesystem configuration file. Is it a bug or am I doing something wrong?
![image](https://github.com/eclipse-edc/Connector/assets/62036653/d9235eed-1b91-4700-ab9f-ee7e014bef0e)

**Comment by MUsman1992** [comment]
Closing this issue. I was actually working on the fix of this bug https://github.com/eclipse-edc/Connector/issues/2997 , When I did some changes to fix it, as a result I got this error. I am closing this thread now and will share my findings in this bug discussion 
https://github.com/eclipse-edc/Connector/issues/2997
