### ISSUE TITLE
QuerySpecValidator fails to catch errors when filterExpression has more than one objects

### ISSUE THREAD

**Issue by DimitrisGk-iel** [eclipse-edc/Connector#3424]
# Bug Report

## Describe the Bug
When we issue a EDC_QUERY_SPEC_TYPE query that has a filterExpresssion with more than one objects, QuerySpecValidator fails to catch it.
![image](https://github.com/eclipse-edc/Connector/assets/30075838/6116e613-e202-498d-a708-ba5129f309a7)
### Expected Behavior
A message that the operandLeft is missing e.g.
[{"message":"mandatory value '[https://w3id.org/edc/v0.0.1/ns/filterExpression/https://w3id.org/edc/v0.0.1/ns/operandLeft'](https://w3id.org/edc/v0.0.1/ns/filterExpression/https://w3id.org/edc/v0.0.1/ns/operandLeft%27) is missing or it is blank","type":"ValidationFailure","path":"[https://w3id.org/edc/v0.0.1/ns/filterExpression/https://w3id.org/edc/v0.0.1/ns/operandLeft","invalidValue":null}]](https://w3id.org/edc/v0.0.1/ns/filterExpression/https://w3id.org/edc/v0.0.1/ns/operandLeft%22,%22invalidValue%22:null%7D])
### Observed Behavior

SEVERE 2023-09-06T00:01:58.1307352 JerseyExtension: Unexpected exception caught
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at org.eclipse.edc.spi.query.Criterion$Builder.build(Criterion.java:132)
	at org.eclipse.edc.core.transform.transformer.to.JsonObjectToCriterionTransformer.transform(JsonObjectToCriterionTransformer.java:51)
	at org.eclipse.edc.core.transform.transformer.to.JsonObjectToCriterionTransformer.transform(JsonObjectToCriterionTransformer.java:29)
	at org.eclipse.edc.core.transform.Transfo

## Steps to Reproduce

1. Issue the above query to the /v3/assets/request endpoint
2. See error

## Context Information
- Used version EDC v0.2.1

## Detailed Description

_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation

CriterionValidator should be run on all filterExpression objects and not just the first one

**Comment by ndr-brt** [comment]
At a glance, the issue should be caused by the wrong definition for the `filterExpression` validator, it should be `verifyArrayItem` instead of `verifyObject`.

https://github.com/eclipse-edc/Connector/blob/f981237b50d63fa07e7a1a4edd1b7fa2e69e1d79/core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/validators/model/QuerySpecValidator.java#L49

**Comment by arnoweiss** [comment]
logically, multiple filterExpressions are AND-chained, right?

**Comment by ndr-brt** [comment]
@arnoweiss yes, they are
