### ISSUE TITLE
Error when using sql extensions: Entity is currently leased!

### ISSUE THREAD

**Issue by Julian-Marco** [eclipse-edc/Connector#3514]
# Bug Report

## Describe the Bug

Working with the SQL extensions for persisting EDC data worked fine with the older versions, say, ``v0.1.0``, because I'm pretty sure that's what we used during this discussion right here: https://github.com/eclipse-edc/Connector/discussions/3242 On the current versions though I always receive an error message stating that the ``Entity is currently leased`` when starting a contract negotiation (it does indeed persist the data though), see the dropdown for details. 

<details open>
<summary>Error message</summary>

    SEVERE 2023-10-05T08:47:57.202475889 JerseyExtension: Unexpected exception caught
    org.eclipse.edc.spi.EdcException: Entity is currently leased!
            at org.eclipse.edc.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:81)
            at org.eclipse.edc.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:56)
            at org.eclipse.edc.sql.lease.SqlLeaseContext.acquireLease(SqlLeaseContext.java:76)
            at org.eclipse.edc.connector.store.sql.contractnegotiation.store.SqlContractNegotiationStore.lambda$findByCorrelationIdAndLease$10(SqlContractNegotiationStore.java:226)
            at org.eclipse.edc.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:74)
            at org.eclipse.edc.connector.store.sql.contractnegotiation.store.SqlContractNegotiationStore.findByCorrelationIdAndLease(SqlContractNegotiationStore.java:215)
            at org.eclipse.edc.connector.service.contractnegotiation.ContractNegotiationProtocolServiceImpl.getNegotiation(ContractNegotiationProtocolServiceImpl.java:222)
            at org.eclipse.edc.connector.service.contractnegotiation.ContractNegotiationProtocolServiceImpl.lambda$notifyRequested$2(ContractNegotiationProtocolServiceImpl.java:70)
            at org.eclipse.edc.spi.result.AbstractResult.compose(AbstractResult.java:169)
            at org.eclipse.edc.connector.service.contractnegotiation.ContractNegotiationProtocolServiceImpl.lambda$notifyRequested$5(ContractNegotiationProtocolServiceImpl.java:70)
            at org.eclipse.edc.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:74)
            at org.eclipse.edc.connector.service.contractnegotiation.ContractNegotiationProtocolServiceImpl.notifyRequested(ContractNegotiationProtocolServiceImpl.java:69)
            at org.eclipse.edc.protocol.dsp.negotiation.api.controller.DspNegotiationApiController.validateAndProcessRequest(DspNegotiationApiController.java:286)
            at org.eclipse.edc.protocol.dsp.api.configuration.message.DspRequestHandlerImpl.createResource(DspRequestHandlerImpl.java:119)
            at org.eclipse.edc.protocol.dsp.negotiation.api.controller.DspNegotiationApiController.initiateNegotiation(DspNegotiationApiController.java:125)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:568)
            at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
            at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
            at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
            at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
            at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
            at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
            at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
            at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
            at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
            at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
            at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
            at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
            at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
            at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
            at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
            at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240)
            at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
            at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
            at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
            at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:357)
            at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
            at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
            at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
            at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
            at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
            at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
            at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
            at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
            at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
            at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
            at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
            at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192)
            at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
            at org.eclipse.jetty.server.Server.handle(Server.java:563)
            at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
            at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
            at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
            at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
            at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
            at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
            at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
            at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
            at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
            at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
            at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:193)
            at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
            at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
            at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
            at java.base/java.lang.Thread.run(Thread.java:833)
    Caused by: java.lang.IllegalStateException: Entity is currently leased!
            at org.eclipse.edc.sql.lease.SqlLeaseContext.lambda$acquireLease$1(SqlLeaseContext.java:82)
            at org.eclipse.edc.transaction.local.LocalTransactionContext.lambda$execute$0(LocalTransactionContext.java:57)
            at org.eclipse.edc.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:74)
            ... 67 more
</details>

This is the relevant part of my ``build.gradle.kts``:

<details open>
<summary>build.gradle.kts</summary>

    implementation("$edcGroupId:asset-index-sql:$edcVersion")
    implementation("$edcGroupId:policy-definition-store-sql:$edcVersion")
    implementation("$edcGroupId:contract-definition-store-sql:$edcVersion")
    implementation("$edcGroupId:contract-negotiation-store-sql:$edcVersion")
    implementation("$edcGroupId:transfer-process-store-sql:$edcVersion")
    implementation("$edcGroupId:sql-pool-apache-commons:$edcVersion")
    implementation("$edcGroupId:transaction-local:$edcVersion")
    implementation("$edcGroupId:transaction-datasource-spi:$edcVersion")
    implementation("$postgresqlGroupId:postgresql:$postgresqlVersion")
</details>

And the relevant part of my ``config.properties``:

<details open>
<summary>config.properties</summary>

    edc.datasource.asset.name=asset
    edc.datasource.asset.user=${POSTGRES_USER}
    edc.datasource.asset.password=${POSTGRES_PASSWORD}
    edc.datasource.asset.url=jdbc:postgresql://edc-db:5432/
    
    edc.datasource.policy.name=policy
    edc.datasource.policy.user=${POSTGRES_USER}
    edc.datasource.policy.password=${POSTGRES_PASSWORD}
    edc.datasource.policy.url=jdbc:postgresql://edc-db:5432/
    
    edc.datasource.contractdefinition.name=contractdefinition
    edc.datasource.contractdefinition.user=${POSTGRES_USER}
    edc.datasource.contractdefinition.password=${POSTGRES_PASSWORD}
    edc.datasource.contractdefinition.url=jdbc:postgresql://edc-db:5432/
    
    edc.datasource.contractnegotiation.name=contractnegotiation
    edc.datasource.contractnegotiation.user=${POSTGRES_USER}
    edc.datasource.contractnegotiation.password=${POSTGRES_PASSWORD}
    edc.datasource.contractnegotiation.url=jdbc:postgresql://edc-db:5432/
    
    edc.datasource.transferprocess.name=transferprocess
    edc.datasource.transferprocess.user=${POSTGRES_USER}
    edc.datasource.transferprocess.password=${POSTGRES_PASSWORD}
    edc.datasource.transferprocess.url=jdbc:postgresql://edc-db:5432/
</details>

Am I missing a module here?

**Comment by ndr-brt** [comment]
this is expected, as described in this DR:
https://github.com/eclipse-edc/Connector/tree/main/docs/developer/decision-records/2023-07-19-sync-commands

> To avoid conflicts with the state machines, every command handler will need to lease the entity before applying the state change. If the lease cannot be obtained, the command will fail.

Every entity modification should be covered by a retry mechanism, as it currently is, so that stacktrace shouldn't be an issue, it should be more silent.

Which version are you on? What are the calls you executed to get this error?

**Comment by Julian-Marco** [comment]
Thanks for the quick response! I tried it with ``0.3.1``, ``0.3.0`` and ``0.2.1`` and the error message is always the same. I just followed the standard procedure. 

1) Hitting the /assets-endpoint with:

````
{
   "@context":{
      "edc":"https://w3id.org/edc/v0.0.1/ns/"
   },
   "@id":"assetId",
   "properties":{
      "name":"product description",
      "contenttype":"application/json"
   },
   "dataAddress":{
         ...
   }
}
```` 

2. Hitting the /policydefinitions-endpoint with:

````
{
   "@context":{
      "edc":"https://w3id.org/edc/v0.0.1/ns/",
      "odrl":"http://www.w3.org/ns/odrl/2/"
   },
   "@id":"aPolicy",
   "policy":{
      "@type":"set",
      "odrl:permission":[
         
      ],
      "odrl:prohibition":[
         
      ],
      "odrl:obligation":[
         
      ]
   }
}
````

3. Hitting the /contractdefinitions-endpoint with:

```` 
{
   "@context":{
      "edc":"https://w3id.org/edc/v0.0.1/ns/"
   },
   "@id":"1",
   "accessPolicyId":"aPolicy",
   "contractPolicyId":"aPolicy",
   "assetsSelector":[
      
   ]
}
````

This works fine and when I restart my EDC, all the JSONS are still there, as it should be when using the respective extensions. The error message arises on the provider side when hitting the /contractnegotations-endpoint of the consumer.

**Comment by ndr-brt** [comment]
does this block the flow or the negotiation happens anyway?

**Comment by Julian-Marco** [comment]
It blocks the flow. The process stays in the ``"REQUESTING"`` state.

````
{
    "@type": "edc:ContractNegotiation",
    "@id": "bc7b104a-b717-4424-909d-31bb69129853",
    "edc:type": "CONSUMER",
    "edc:protocol": "dataspace-protocol-http",
    "edc:state": "REQUESTING",
    "edc:counterPartyId": "provider",
    "edc:counterPartyAddress": "http://localhost:8282/protocol",
    "edc:callbackAddresses": [],
    "edc:createdAt": 1696593646500,
    "@context": {
        "dct": "https://purl.org/dc/terms/",
        "edc": "https://w3id.org/edc/v0.0.1/ns/",
        "dcat": "https://www.w3.org/ns/dcat/",
        "odrl": "http://www.w3.org/ns/odrl/2/",
        "dspace": "https://w3id.org/dspace/v0.8/"
    }
}
````

**Comment by ndr-brt** [comment]
ok, but it should try again later right? the State Machine are made for trying again until they either succeed or the negotiation gets TERMINATED

another maybe silly question... are you running two separate connectors with two separate databases right?

**Comment by Julian-Marco** [comment]
> another maybe silly question... are you running two separate connectors with two separate databases right?

Damn, that question is on point actually. The consumer connector I'm using right now is merely for testing purposes, so it's basically a copy of the provider connector with different ports. So yes, it's two different connectors, but they share the same database. Didn't think that this could be an issue since the provider is the one registering the asset and the database doesn't contain anything else besides that. I probably did indeed use two databases the last time I tested this thorougly so that's why it worked back then. 

So yeah, erasing the sql modules (quicker than setting up another db for now) from the consumer connector solved it apparently. Sorry, my bad!

**Comment by sfl0r3nz05** [comment]
@Julian-Marco, I am having the same problem when I try to start a negotiation from a consumer. Could you indicate me how you erased the SQL modules? Thanks !!!

**Comment by Julian-Marco** [comment]
> @Julian-Marco, I am having the same problem when I try to start a negotiation from a consumer. Could you indicate me how you erased the SQL modules? Thanks !!!

I simply meant that I temporarly deleted the reference to the sql modules from the build gradle file of the consumer connector for testing purposes because two connectors can't share the same database. That way, the consumer connector didn't even try to connect to any database. 

But obviously it's much more advisable to simply use two databases instead and adjust the configuration for the consumer connector appropriately.

**Comment by sfl0r3nz05** [comment]
> > @Julian-Marco, I am having the same problem when I try to start a negotiation from a consumer. Could you indicate me how you erased the SQL modules? Thanks !!!
> 
> I simply meant that I temporarly deleted the reference to the sql modules from the build gradle file of the consumer connector for testing purposes because two connectors can't share the same database. That way, the consumer connector didn't even try to connect to any database.
> 
> But obviously it's much more advisable to simply use two databases instead and adjust the configuration for the consumer connector appropriately.

Thanks @Julian-Marco for your quick response. I am testing on docker and as you say, each connector uses its own DB container. I guess my issue goes the other way.

**Comment by Julian-Marco** [comment]
Maybe you missed a couple of necessary modules. Do you use everything listed here? 

    implementation("$edcGroupId:asset-index-sql:$edcVersion")
    implementation("$edcGroupId:policy-definition-store-sql:$edcVersion")
    implementation("$edcGroupId:contract-definition-store-sql:$edcVersion")
    implementation("$edcGroupId:contract-negotiation-store-sql:$edcVersion")
    implementation("$edcGroupId:transfer-process-store-sql:$edcVersion")

    implementation("$edcGroupId:sql-pool-apache-commons:$edcVersion")
    implementation("$edcGroupId:transaction-local:$edcVersion")
    implementation("$edcGroupId:transaction-datasource-spi:$edcVersion")
    implementation("$postgresqlGroupId:postgresql:$postgresqlVersion")

**Comment by sfl0r3nz05** [comment]
> Maybe you missed a couple of necessary modules. Do you use everything listed here?
> 
> ```
> implementation("$edcGroupId:asset-index-sql:$edcVersion")
> implementation("$edcGroupId:policy-definition-store-sql:$edcVersion")
> implementation("$edcGroupId:contract-definition-store-sql:$edcVersion")
> implementation("$edcGroupId:contract-negotiation-store-sql:$edcVersion")
> implementation("$edcGroupId:transfer-process-store-sql:$edcVersion")
> 
> implementation("$edcGroupId:sql-pool-apache-commons:$edcVersion")
> implementation("$edcGroupId:transaction-local:$edcVersion")
> implementation("$edcGroupId:transaction-datasource-spi:$edcVersion")
> implementation("$postgresqlGroupId:postgresql:$postgresqlVersion")
> ```

Thanks again @Julian-Marco, I am using docker image `edc-dev:6.0.0` of the community version of sovity. I will inspect if this modules are included.

**Comment by arnoweiss** [comment]
I'm observing that the "Entity is currently leased" error also occurs when the HPA scales up the pods to more than one. Has anyone else experienced this?

**Comment by arnoweiss** [comment]
Nope, persists until this day.
