### ISSUE TITLE
Using custom interceptors of okhttp3 causes error if chunked transfer is enabled

### ISSUE THREAD

**Issue by iwasakims** [eclipse-edc/Connector#3599]
# Bug Report

## Describe the Bug

Using custom okhttp3 client with interceptors (e.g. logging-interceptor) causes error if chunked transfer is enabled.

```
SEVERE 2023-11-13T11:21:24.160252997 Error writing HTTP data Test asset to endpoint http://localhost:4000/api/consumer/store for request: Request{method=POST, url=http://localhost:4000/api/consumer/store}
java.io.IOException: closed
        at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:154)
        at java.base/java.io.InputStream.transferTo(InputStream.java:782)
        at org.eclipse.edc.connector.dataplane.http.pipeline.ChunkedTransferRequestBody.writeTo(ChunkedTransferRequestBody.java:43)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:202)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at dev.failsafe.okhttp.FailsafeCall.lambda$execute$0(FailsafeCall.java:117)
        at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
        at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
        at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
        at dev.failsafe.CallImpl.execute(CallImpl.java:33)
        at dev.failsafe.okhttp.FailsafeCall.execute(FailsafeCall.java:121)
        at org.eclipse.edc.connector.core.base.EdcHttpClientImpl.execute(EdcHttpClientImpl.java:59)
        at org.eclipse.edc.connector.core.base.EdcHttpClientImpl.execute(EdcHttpClientImpl.java:51)
        at org.eclipse.edc.connector.dataplane.http.pipeline.HttpDataSink.transferParts(HttpDataSink.java:44)
        at org.eclipse.edc.connector.dataplane.util.sink.ParallelSink.lambda$transfer$3(ParallelSink.java:82)
        at org.eclipse.edc.spi.telemetry.Telemetry.lambda$contextPropagationMiddleware$2(Telemetry.java:102)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

There is no issue if chunked transfer is desabled for the destination by setting `"nonChunkedTransfer": "true"`.

## Context Information

- Used version EDC v0.3.1 with modified `OkHttpClientFactory`
- OS: Ubuntu 22.04

## Possible Implementation

Adding overridden `body` method to `ChunkedTransferRequestBody` to expose body content to interceptors.

**Comment by ndr-brt** [comment]
could you please provide the code used to cause that stacktrace?

**Comment by iwasakims** [comment]
> could you please provide the code used to cause that stacktrace?

The stack trace was emitted by connector of [transfer samples](https://github.com/eclipse-edc/Samples/tree/main/transfer) built against OkHttpClientFactory modified like
https://github.com/iwasakims/DataSpaceConnector/commit/162690cacd2c287f8a0e70ba5bd237a8ec1d7e85
