### ISSUE TITLE
Can create policy without `action` which leads to broken fetch all policies with `policiydefinitions/request`

### ISSUE THREAD

**Issue by matgnt** [eclipse-edc/Connector#3661]
When someone creates a wrong policy, e.g. with a missing action field, thereafter all queries to get a list of policies fails.

error
```
edc-dev-env-provider-control-plane-1  | Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.edc.policy.model.Action.getType()" because "action" is null
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.core.transform.transformer.from.JsonObjectFromPolicyTransformer$Visitor.visitAction(JsonObjectFromPolicyTransformer.java:226)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.core.transform.transformer.from.JsonObjectFromPolicyTransformer$Visitor.visitRule(JsonObjectFromPolicyTransformer.java:204)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.core.transform.transformer.from.JsonObjectFromPolicyTransformer$Visitor.visitPermission(JsonObjectFromPolicyTransformer.java:167)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.core.transform.transformer.from.JsonObjectFromPolicyTransformer$Visitor.visitPermission(JsonObjectFromPolicyTransformer.java:86)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.policy.model.Permission.accept(Permission.java:43)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.core.transform.transformer.from.JsonObjectFromPolicyTransformer$Visitor.lambda$visitPolicy$1(JsonObjectFromPolicyTransformer.java:145)
edc-dev-env-provider-control-plane-1  |         at java.base/java.util.ArrayList.forEach(Unknown Source)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.core.transform.transformer.from.JsonObjectFromPolicyTransformer$Visitor.visitPolicy(JsonObjectFromPolicyTransformer.java:145)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.core.transform.transformer.from.JsonObjectFromPolicyTransformer$Visitor.visitPolicy(JsonObjectFromPolicyTransformer.java:86)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.policy.model.Policy.accept(Policy.java:89)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.core.transform.transformer.from.JsonObjectFromPolicyTransformer.transform(JsonObjectFromPolicyTransformer.java:80)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.core.transform.transformer.from.JsonObjectFromPolicyTransformer.transform(JsonObjectFromPolicyTransformer.java:70)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.core.transform.TransformerContextImpl.transform(TransformerContextImpl.java:60)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.connector.api.management.policy.transform.JsonObjectFromPolicyDefinitionTransformer.transform(JsonObjectFromPolicyDefinitionTransformer.java:47)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.connector.api.management.policy.transform.JsonObjectFromPolicyDefinitionTransformer.transform(JsonObjectFromPolicyDefinitionTransformer.java:30)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.core.transform.TransformerContextImpl.transform(TransformerContextImpl.java:60)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.core.transform.TypeTransformerRegistryImpl.transform(TypeTransformerRegistryImpl.java:55)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.connector.api.management.policy.PolicyDefinitionApiController.lambda$queryPolicyDefinitions$0(PolicyDefinitionApiController.java:81)
edc-dev-env-provider-control-plane-1  |         at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
edc-dev-env-provider-control-plane-1  |         at org.eclipse.edc.sql.SqlQueryExecutor$1.tryAdvance(SqlQueryExecutor.java:135)
```

policy
```json
{
    "@context": {
        "dct": "https://purl.org/dc/terms/",
        "tx": "https://w3id.org/tractusx/v0.0.1/ns/",
        "edc": "https://w3id.org/edc/v0.0.1/ns/",
        "dcat": "https://www.w3.org/ns/dcat/",
        "odrl": "http://www.w3.org/ns/odrl/2/",
        "dspace": "https://w3id.org/dspace/v0.8/"
    },
    "@id": "e89bfcab-d454-4ffd-b85d-fc069abfe0ef",
    "policy": {
        "@type": "Policy",
        "odrl:permission": [
            {
                "@type": "LogicalConstraint",
                "odrl:and": [
                    {
                        "@type": "Constraint",
                        "odrl:leftOperand": "PURPOSE",
                        "odrl:operator": {
                            "@id": "odrl:eq"
                        },
                        "odrl:rightOperand": "abc"
                    },
                    {
                        "@type": "Constraint",
                        "odrl:leftOperand": "PURPOSE",
                        "odrl:operator": {
                            "@id": "odrl:eq"
                        },
                        "odrl:rightOperand": "ID 3.1 Trace"
                    }
                ]
            }
        ]
    }
}
```

Examples attached.

This seems to be very similar to the bug we once had with breaking the catalog with a single wrong item - at least from an outside perspective.

Tested with tractusx-edc 0.5.1
@wolf4ood  already confirmed with upstream EDC 0.4.1

Expected behavior:
Invalid policies can not be created. And as backup, the listing should only not include the broken policy, but still be able to query the valid ones.

tractusx-edc issue: https://github.com/eclipse-tractusx/tractusx-edc/issues/883

--
Matthias Binzer

**Comment by saschaisele-zf** [comment]
Hello,
I will take a look at this.
Just assign me here.

**Comment by matgnt** [comment]
Interesting that this is not handled as a bug, but a feature request ;-)

**Comment by ndr-brt** [comment]
@matgnt a bug is something that prevents a working flows of the application to work as expected. in this case is a missing validation on input policy, because a policy without `action` should not exist by definition ([A Rule MUST have one action property value of type Action.](https://www.w3.org/TR/odrl-model/#rule)), so, pushing one of these in the management api is an unexpected behavior.
adding the validation on the input will prevent this case from happening.

**Comment by matgnt** [comment]
Thanks for the details. In that sense, I still think I did report a bug. I did not report that validation is missing.
I did report that I add a policy and can not fetch all policies thereafter - which I would consider what you just explained with "prevents a working flows of the application to work as expected." I guess this is not considered "as expected".
