### ISSUE TITLE
Policy Definition API accepts policy that causes exception when calling catalog and refuses other policy

### ISSUE THREAD

**Issue by sfranke43** [eclipse-edc/Connector#3687]
When calling the policy definition API with: 
`curl -d '{
           "@context": {
             "edc": "https://w3id.org/edc/v0.0.1/ns/",
             "odrl": "http://www.w3.org/ns/odrl/2/"
           },
           "@id": "test_data_medical(1).json_policy",
           "policy": {
            "@type": "set",
            "@context": "http://www.w3.org/ns/odrl.jsonld",
            "permission": [{"target":"test_data_medical(1).json", "action": "transform","constraints": [{ "leftOperand": "product",
            "operator": "eq",
            "rightOperand": "allergy", 
            "comment": "keep_data"},{ "leftOperand": "product",
            "operator": "eq",
            "rightOperand": " symptoms", 
            "comment": "keep_data"},{ "leftOperand": "product",
            "operator": "eq",
            "rightOperand": " previous sickness", 
            "comment": "keep_data"}]}],
   "prohibition":[{"target":"test_data_medical(1).json", "action": "transform","constraint": [{ "leftOperand": "dateTime",
            "operator": "eq",
            "rightOperand": "2024-05-12", 
            "comment": "save_until"}]}], 
        "obligation":[{"target":"test_data_medical(1).json", "action": "transform","constraint": [{ "leftOperand": "resolution",
            "operator": "eq",
            "rightOperand": "allergy:2", 
            "comment": "abstractLvl"},{ "leftOperand": "resolution",
            "operator": "eq",
            "rightOperand": " symptoms:1", 
            "comment": "abstractLvl"},{ "leftOperand": "resolution",
            "operator": "eq",
            "rightOperand": " previous sickness:3", 
            "comment": "abstractLvl"}]},{"target":"test_data_medical(1).json", "action": "transform","constraint": [{ "leftOperand": "product",
            "operator": "eq",
            "rightOperand": "allergy", 
            "comment": "differantialPrivacy"},{ "leftOperand": "product",
            "operator": "eq",
            "rightOperand": " symptoms", 
            "comment": "differantialPrivacy"}]}]
           }
         }' -H 'content-type: application/json' http://localhost:19193/management/v2/assets \
         -s | jq`

Expected behavior: accepting the policy

Real behavior: 
`<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 Bad Request</title>
</head>
<body><h2>HTTP ERROR 400 Bad Request</h2>
<table>
<tr><th>URI:</th><td>/management/v2/policydefinitions</td></tr>
<tr><th>STATUS:</th><td>400</td></tr>
<tr><th>MESSAGE:</th><td>Bad Request</td></tr>
<tr><th>SERVLET:</th><td>EDC-management</td></tr>
</table>
<hr/><a href="https://eclipse.org/jetty">Powered by Jetty:// 11.0.16</a><hr/>

</body>
</html>`

Without adding the "context" in the policy and using my own made up strings as constarints, the policy is accepted. However when trying to call the catalog, it return that "action" is Null and crashes.

**Comment by ndr-brt** [comment]
You are not specifying the `@context` correctly, the `@vocab` attribute is needed because there are not-namespaced properties (e.g. `policy`) and json-ld needs to know what's the default IRL to use.
Please try with:
```json
{
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "@id": "test_data_medical(1).json_policy",
  "policy": {
    "@type": "set",
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "permission": [
      {
        "target": "test_data_medical(1).json",
        "action": "transform",
        "constraints": [
          {
            "leftOperand": "product",
            "operator": "eq",
            "rightOperand": "allergy",
            "comment": "keep_data"
          },
          {
            "leftOperand": "product",
            "operator": "eq",
            "rightOperand": " symptoms",
            "comment": "keep_data"
          },
          {
            "leftOperand": "product",
            "operator": "eq",
            "rightOperand": " previous sickness",
            "comment": "keep_data"
          }
        ]
      }
    ],
    "prohibition": [
      {
        "target": "test_data_medical(1).json",
        "action": "transform",
        "constraint": [
          {
            "leftOperand": "dateTime",
            "operator": "eq",
            "rightOperand": "2024-05-12",
            "comment": "save_until"
          }
        ]
      }
    ],
    "obligation": [
      {
        "target": "test_data_medical(1).json",
        "action": "transform",
        "constraint": [
          {
            "leftOperand": "resolution",
            "operator": "eq",
            "rightOperand": "allergy:2",
            "comment": "abstractLvl"
          },
          {
            "leftOperand": "resolution",
            "operator": "eq",
            "rightOperand": " symptoms:1",
            "comment": "abstractLvl"
          },
          {
            "leftOperand": "resolution",
            "operator": "eq",
            "rightOperand": " previous sickness:3",
            "comment": "abstractLvl"
          }
        ]
      },
      {
        "target": "test_data_medical(1).json",
        "action": "transform",
        "constraint": [
          {
            "leftOperand": "product",
            "operator": "eq",
            "rightOperand": "allergy",
            "comment": "differantialPrivacy"
          },
          {
            "leftOperand": "product",
            "operator": "eq",
            "rightOperand": " symptoms",
            "comment": "differantialPrivacy"
          }
        ]
      }
    ]
  }
}
```

note: when you get error like these is because the json-ld library is not able to expand the body, eventually you can try it out on the [json-ld playground](https://json-ld.org/playground/) manually

**Comment by sfranke43** [comment]
I get the same response for that. 

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 Bad Request</title>
</head>
<body><h2>HTTP ERROR 400 Bad Request</h2>
<table>
<tr><th>URI:</th><td>/management/v2/policydefinitions</td></tr>
<tr><th>STATUS:</th><td>400</td></tr>
<tr><th>MESSAGE:</th><td>Bad Request</td></tr>
<tr><th>SERVLET:</th><td>EDC-management</td></tr>
</table>
<hr/><a href="https://eclipse.org/jetty">Powered by Jetty:// 11.0.16</a><hr/>

</body>
</html>

**Comment by ndr-brt** [comment]
could you please add some details, as edc version? any stack traces? OS?

**Comment by sfranke43** [comment]
I am on EDC release 0.3.1, Windows 10. I have slightly edited the http dataplane and my goal is to pass the variables of the contract onto my dataplane. the stack trace is:

```
WARNING 2023-12-05T16:50:10.8198325 Error expanding JSON-LD structure
JsonLdError[code=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED]., message=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].]
        at com.apicatalog.jsonld.context.ActiveContextBuilder.fetch(ActiveContextBuilder.java:539)
        at com.apicatalog.jsonld.context.ActiveContextBuilder.create(ActiveContextBuilder.java:174)
        at com.apicatalog.jsonld.expansion.ObjectExpansion.initLocalContext(ObjectExpansion.java:200)
        at com.apicatalog.jsonld.expansion.ObjectExpansion.expand(ObjectExpansion.java:102)
        at com.apicatalog.jsonld.expansion.Expansion.compute(Expansion.java:119)
        at com.apicatalog.jsonld.expansion.ObjectExpansion1314.expand(ObjectExpansion1314.java:946)
        at com.apicatalog.jsonld.expansion.ObjectExpansion.expand(ObjectExpansion.java:121)
        at com.apicatalog.jsonld.expansion.Expansion.compute(Expansion.java:119)
        at com.apicatalog.jsonld.processor.ExpansionProcessor.expand(ExpansionProcessor.java:124)
        at com.apicatalog.jsonld.api.ExpansionApi.get(ExpansionApi.java:131)
        at org.eclipse.edc.jsonld.TitaniumJsonLd.expand(TitaniumJsonLd.java:67)
        at org.eclipse.edc.web.jersey.jsonld.JerseyJsonLdInterceptor.aroundReadFrom(JerseyJsonLdInterceptor.java:52)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:49)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072)
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:919)
        at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:290)
        at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:73)
        at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:56)
        at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:50)
        at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:68)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:109)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:357)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.Server.handle(Server.java:563)
        at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: JsonLdError[code=The document could not be loaded or parsed [code=LOADING_DOCUMENT_FAILED]., message=URL scheme [http] is not supported.]
        at com.apicatalog.jsonld.loader.SchemeRouter.loadDocument(SchemeRouter.java:59)
        at org.eclipse.edc.jsonld.TitaniumJsonLd$CachedDocumentLoader.loadDocument(TitaniumJsonLd.java:146)
        at com.apicatalog.jsonld.context.ActiveContextBuilder.fetch(ActiveContextBuilder.java:535)
        ... 64 more
```

**Comment by ndr-brt** [comment]
EDC is not fully supported to run on windows machine, please run it into a containered environment on linux.
another advice is to update to the latest version (0.4.1)

**Comment by ndr-brt** [comment]
It should have been solved by #3670, could you try it again with the latest main commit?
