### ISSUE TITLE
bug: transfer-data-plane - Initiate Transfer Process Fails

### ISSUE THREAD

**Issue by hemantxpatel** [eclipse-edc/Connector#3810]
# Bug Report
Initiate Transfer Process API `/management/v2/transferprocesses` fails.

## Describe the Bug
While initiating transfer, an access token using a private key is generated to initiate the dataflow.
Private key alias (against which private key is stored in Vault) is provided via config `edc.transfer.proxy.token.signer.privatekey.alias` which is not mandatory and has default value null.
When above config is not provided to connector, it tries to resolve a vault secret with null value and hence it fails.

Code which causes issue: [TransferDataPlaneCoreExtension.java](https://github.com/eclipse-edc/Connector/blob/98b5e8ac71935545a7cc98c3782b879b2545a0d4/extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneCoreExtension.java#L131C5-L137C6)
```
private Supplier<PrivateKey> getPrivateKeySupplier(ServiceExtensionContext context, String privKeyAlias) {
        return () -> privateKeyResolver.resolvePrivateKey(privKeyAlias)
                .orElse(f -> {
                    context.getMonitor().warning(f.getFailureDetail());
                    return null;
                });
    }
```
Since `privKeyAlias` was not provided, `privateKeyResolver.resolvePrivateKey(privKeyAlias)` throws `NullPointerException`.

### Expected Behavior

When privateKeyAlias is not provided, it should use a default private key. Since it is not mandatory.

### Observed Behavior

Stack Trace during transfer process
```
DEBUG 2024-01-30T06:35:53.621882064 TransferProcess: ID b7c8d6b6-1b43-4a32-b748-381e17dfe7ee. Initiate data flow
java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
        at java.base/java.net.URLEncoder.encode(Unknown Source)
        at org.eclipse.edc.vault.hashicorp.HashicorpVaultClient.getSecretUrl(HashicorpVaultClient.java:186)
        at org.eclipse.edc.vault.hashicorp.HashicorpVaultClient.getSecretValue(HashicorpVaultClient.java:65)
        at org.eclipse.edc.vault.hashicorp.HashicorpVault.resolveSecret(HashicorpVault.java:41)
        at org.eclipse.edc.spi.security.VaultPrivateKeyResolver.resolveInternal(VaultPrivateKeyResolver.java:42)
        at org.eclipse.edc.spi.security.AbstractPrivateKeyResolver.resolvePrivateKey(AbstractPrivateKeyResolver.java:41)
        at org.eclipse.edc.connector.transfer.dataplane.TransferDataPlaneCoreExtension.lambda$getPrivateKeySupplier$3(TransferDataPlaneCoreExtension.java:132)
        at org.eclipse.edc.token.JwtGenerationService.generate(JwtGenerationService.java:45)
        at org.eclipse.edc.connector.transfer.dataplane.proxy.ConsumerPullDataPlaneProxyResolver.lambda$generateAccessToken$4(ConsumerPullDataPlaneProxyResolver.java:89)
        at org.eclipse.edc.spi.result.AbstractResult.compose(AbstractResult.java:169)
        at org.eclipse.edc.connector.transfer.dataplane.proxy.ConsumerPullDataPlaneProxyResolver.generateAccessToken(ConsumerPullDataPlaneProxyResolver.java:86)
        at org.eclipse.edc.connector.transfer.dataplane.proxy.ConsumerPullDataPlaneProxyResolver.lambda$toDataAddress$2(ConsumerPullDataPlaneProxyResolver.java:66)
        at org.eclipse.edc.spi.result.AbstractResult.compose(AbstractResult.java:169)
        at org.eclipse.edc.connector.transfer.dataplane.proxy.ConsumerPullDataPlaneProxyResolver.toDataAddress(ConsumerPullDataPlaneProxyResolver.java:66)
        at org.eclipse.edc.connector.transfer.dataplane.flow.ConsumerPullTransferDataFlowController.lambda$initiateFlow$1(ConsumerPullTransferDataFlowController.java:63)
        at java.base/java.util.Optional.map(Unknown Source)
        at org.eclipse.edc.connector.transfer.dataplane.flow.ConsumerPullTransferDataFlowController.initiateFlow(ConsumerPullTransferDataFlowController.java:63)
        at org.eclipse.edc.connector.transfer.flow.DataFlowManagerImpl.lambda$initiate$0(DataFlowManagerImpl.java:59)
        at java.base/java.util.Optional.map(Unknown Source)
        at org.eclipse.edc.connector.transfer.flow.DataFlowManagerImpl.chooseControllerAndApply(DataFlowManagerImpl.java:86)
        at org.eclipse.edc.connector.transfer.flow.DataFlowManagerImpl.initiate(DataFlowManagerImpl.java:59)
        at org.eclipse.edc.connector.transfer.process.TransferProcessManagerImpl.lambda$processStarting$14(TransferProcessManagerImpl.java:310)
        at org.eclipse.edc.statemachine.retry.StatusResultRetryProcess.process(StatusResultRetryProcess.java:48)
        at org.eclipse.edc.statemachine.retry.RetryProcess.execute(RetryProcess.java:71)
        at org.eclipse.edc.connector.transfer.process.TransferProcessManagerImpl.processStarting(TransferProcessManagerImpl.java:315)
        at org.eclipse.edc.spi.telemetry.Telemetry.lambda$contextPropagationMiddleware$0(Telemetry.java:73)
        at org.eclipse.edc.statemachine.ProcessorImpl.lambda$process$1(ProcessorImpl.java:55)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.ReduceOps$5.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.ReduceOps$5.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.count(Unknown Source)
        at org.eclipse.edc.statemachine.ProcessorImpl.process(ProcessorImpl.java:62)
        at java.base/java.util.stream.ReferencePipeline$5$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.LongPipeline.reduce(Unknown Source)
        at java.base/java.util.stream.LongPipeline.sum(Unknown Source)
        at org.eclipse.edc.statemachine.StateMachineManager.performLogic(StateMachineManager.java:110)
        at org.eclipse.edc.statemachine.StateMachineManager.lambda$loop$2(StateMachineManager.java:101)
        at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
        at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:193)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
SEVERE 2024-01-30T06:42:39.013773565 TransferProcess: ID b7c8d6b6-1b43-4a32-b748-381e17dfe7ee. Fatal error while Initiate data flow. Error details: Unable to process transfer b7c8d6b6-1b43-4a32-b748-381e17dfe7ee. Data flow controller throws an exception: Cannot invoke "String.length()" because "<parameter1>" is null
WARNING 2024-01-30T06:42:39.014937674 Unable to process transfer b7c8d6b6-1b43-4a32-b748-381e17dfe7ee. Data flow controller throws an exception: Cannot invoke "String.length()" because "<parameter1>" is null
DEBUG 2024-01-30T06:42:39.052486906 [TransferProcessManagerImpl] TransferProcess b7c8d6b6-1b43-4a32-b748-381e17dfe7ee is now in state TERMINATING
DEBUG 2024-01-30T06:42:39.060849516 TransferProcess: ID b7c8d6b6-1b43-4a32-b748-381e17dfe7ee. Terminate data flow
```

## Steps to Reproduce

1. Initiate a transfer process.
2. Check Transfer Process State which is `TERMINATED`
3. Check connector logs.

## Context Information

- Used version: EDC v0.5.0
- OS: Windows

**Comment by ndr-brt** [comment]
I think the behavior here should be that, when there's no private key the (consumer pull) transfer should not happen, likely providing a better error message. The problem is here:
https://github.com/eclipse-edc/Connector/blob/98b5e8ac71935545a7cc98c3782b879b2545a0d4/core/common/token-core/src/main/java/org/eclipse/edc/token/JwtGenerationService.java#L45

when the returned `privateKey` is null, this token generation service should return a failed `Result` so the error will be propagated up to the data flow controller.

In addition, maybe we could ensure that the `ConsumerPullTransferDataFlowController` is not registered when the setting is missing.

**Comment by wolf4ood** [comment]
I agree, previously we generated key pair on the fly if missing if i remember correctly. Since it's not there anymore we should make the config mandatory or not registering `ConsumerPullTransferDataFlowController` if the key it's not there

**Comment by hemantxpatel** [comment]
Hi @ndr-brt , is there any workaround for this.
1. Without using config `edc.transfer.proxy.token.signer.privatekey.alias` 
2. If this config `edc.transfer.proxy.token.signer.privatekey.alias` needs to be defined, what value should be used against this alias in vault.

**Comment by ndr-brt** [comment]
> 1. Without using config `edc.transfer.proxy.token.signer.privatekey.alias`

If that config is not set, the connector won't be able to provide "consumer pull" transfers, because for those there's the need to sign the token

> 2. If this config `edc.transfer.proxy.token.signer.privatekey.alias` needs to be defined, what value should be used against this alias in vault.

the alias should be the key with which the private key has been stored in the vault
