### ISSUE TITLE
NPE when consumer tries to terminate a `REQUESTED` negotiation

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#3814]
# Bug Report

## Describe the Bug

When a consumer tries to manually terminate a negotiation that is in the `REQUESTED` state, it gets a NPE:

```
consumer-connector-1  | java.lang.NullPointerException: Value in JsonObjects name/value pair cannot be null
consumer-connector-1  | 	at org.glassfish.json.JsonObjectBuilderImpl.validateValue(JsonObjectBuilderImpl.java:223)
consumer-connector-1  | 	at org.glassfish.json.JsonObjectBuilderImpl.add(JsonObjectBuilderImpl.java:88)
consumer-connector-1  | 	at org.eclipse.edc.protocol.dsp.negotiation.transform.from.JsonObjectFromContractNegotiationTerminationMessageTransformer.transform(JsonObjectFromContractNegotiationTerminationMessageTransformer.java:52)
consumer-connector-1  | 	at org.eclipse.edc.protocol.dsp.negotiation.transform.from.JsonObjectFromContractNegotiationTerminationMessageTransformer.transform(JsonObjectFromContractNegotiationTerminationMessageTransformer.java:37)
consumer-connector-1  | 	at org.eclipse.edc.core.transform.TransformerContextImpl.transform(TransformerContextImpl.java:60)
consumer-connector-1  | 	at org.eclipse.edc.core.transform.TypeTransformerRegistryImpl.transform(TypeTransformerRegistryImpl.java:55)
consumer-connector-1  | 	at org.eclipse.edc.protocol.dsp.serialization.JsonLdRemoteMessageSerializerImpl.serialize(JsonLdRemoteMessageSerializerImpl.java:58)
consumer-connector-1  | 	at org.eclipse.edc.protocol.dsp.dispatcher.PostDspHttpRequestFactory.createRequest(PostDspHttpRequestFactory.java:44)
consumer-connector-1  | 	at org.eclipse.edc.protocol.dsp.dispatcher.DspHttpRemoteMessageDispatcherImpl.dispatch(DspHttpRemoteMessageDispatcherImpl.java:83)
consumer-connector-1  | 	at org.eclipse.edc.connector.core.base.RemoteMessageDispatcherRegistryImpl.dispatch(RemoteMessageDispatcherRegistryImpl.java:48)
consumer-connector-1  | 	at org.eclipse.edc.connector.contract.negotiation.AbstractContractNegotiationManager.lambda$dispatch$7(AbstractContractNegotiationManager.java:110)
consumer-connector-1  | 	at org.eclipse.edc.statemachine.retry.CompletableFutureRetryProcess.process(CompletableFutureRetryProcess.java:50)
consumer-connector-1  | 	at org.eclipse.edc.statemachine.retry.RetryProcess.execute(RetryProcess.java:71)
consumer-connector-1  | 	at org.eclipse.edc.connector.contract.negotiation.AbstractContractNegotiationManager.processTerminating(AbstractContractNegotiationManager.java:87)
consumer-connector-1  | 	at org.eclipse.edc.spi.telemetry.Telemetry.lambda$contextPropagationMiddleware$0(Telemetry.java:73)
consumer-connector-1  | 	at org.eclipse.edc.statemachine.ProcessorImpl.lambda$process$1(ProcessorImpl.java:55)
```

### Expected Behavior

no NPE, message is correctly sent to provider

## Context Information

_Add any other context about the problem here._

- EDC 0.5.0

## Possible Implementation

here we have a problem, because the consumer doesn't have the `providerPid` yet so it won't be able to perform the correct request with the ID.
An alternative would be to deny termination when the consumer doesn't have the provider id yet.

**Comment by ndr-brt** [comment]
note: likely we'll need to start deserializing the response body, that returns the `providerPid`, so after the successful `ContractRequestedMessage` sent, the consumer will already know the `providerPid`:
https://docs.internationaldataspaces.org/ids-knowledgebase/v/dataspace-protocol/contract-negotiation/contract.negotiation.binding.https#id-2.5.1-post
